name: pv-kpi
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.12
  - pandas>=2.0
  - numpy>=1.24
  - matplotlib>=3.7
  - openpyxl>=3.1
  - pvlib>=0.10
  - pyarrow>=12.0
  - tqdm>=4.65
  - ipykernel>=6.22
  - statsmodels>=0.14
  - scikit-learn>=1.3
  - pip
  - pip:
    - -r requirements.txt
